package training

import (
	"fmt"
	"log/slog"
	"math/rand"
	"strings"
	"sync"
	"time"
)

// SelfPlayConfig controls the self-play training behavior.
type SelfPlayConfig struct {
	IdleTimeout   time.Duration // how long to wait before starting (default 60s)
	MaxPairsPerRun int          // max training pairs per idle session (default 100)
	MinQuality    float64       // minimum quality threshold for a pair (default 0.7)
}

// DefaultSelfPlayConfig returns sensible defaults for self-play.
func DefaultSelfPlayConfig() SelfPlayConfig {
	return SelfPlayConfig{
		IdleTimeout:    60 * time.Second,
		MaxPairsPerRun: 100,
		MinQuality:     0.7,
	}
}

// KnowledgeChunk is a piece of knowledge that self-play can generate questions about.
type KnowledgeChunk struct {
	Content string
	Domain  string
}

// QuestionAnswerPair is a training pair generated by self-play.
type QuestionAnswerPair struct {
	Question   string  `json:"question"`
	Answer     string  `json:"answer"`
	Source     string  `json:"source"` // "self-play"
	Quality    float64 `json:"quality"`
	GeneratedAt time.Time `json:"generated_at"`
}

// SelfPlay generates synthetic training data during idle time.
// It picks random knowledge chunks, generates questions about them,
// answers using the full cognitive pipeline, and validates answers
// against the source knowledge using embedding similarity.
type SelfPlay struct {
	mu     sync.Mutex
	config SelfPlayConfig

	// Dependencies (set before calling Run)
	Knowledge    []KnowledgeChunk
	GenerateQA   func(chunk string) ([]QuestionAnswerPair, error) // generates Q&A from a chunk
	ValidatePair func(pair QuestionAnswerPair, source string) float64 // returns quality 0-1
	StorePair    func(pair QuestionAnswerPair) // stores a validated pair

	// Stats
	TotalGenerated int
	TotalAccepted  int
	TotalRejected  int
	LastRun        time.Time
	Running        bool
}

// NewSelfPlay creates a new self-play trainer.
func NewSelfPlay(config SelfPlayConfig) *SelfPlay {
	return &SelfPlay{
		config: config,
	}
}

// RunOnce executes a single self-play session, generating training pairs
// from available knowledge chunks. Returns the number of accepted pairs.
func (sp *SelfPlay) RunOnce() int {
	sp.mu.Lock()
	if sp.Running {
		sp.mu.Unlock()
		return 0
	}
	sp.Running = true
	sp.mu.Unlock()

	defer func() {
		sp.mu.Lock()
		sp.Running = false
		sp.LastRun = time.Now()
		sp.mu.Unlock()
	}()

	if len(sp.Knowledge) == 0 || sp.GenerateQA == nil || sp.StorePair == nil {
		return 0
	}

	accepted := 0
	maxPairs := sp.config.MaxPairsPerRun

	// Shuffle knowledge chunks for variety
	chunks := make([]KnowledgeChunk, len(sp.Knowledge))
	copy(chunks, sp.Knowledge)
	rand.Shuffle(len(chunks), func(i, j int) {
		chunks[i], chunks[j] = chunks[j], chunks[i]
	})

	for _, chunk := range chunks {
		if accepted >= maxPairs {
			break
		}

		// Generate Q&A pairs from this chunk
		pairs, err := sp.GenerateQA(chunk.Content)
		if err != nil {
			slog.Debug("selfplay: generate failed", "error", err)
			continue
		}

		for _, pair := range pairs {
			if accepted >= maxPairs {
				break
			}

			pair.Source = "self-play"
			pair.GeneratedAt = time.Now()

			// Validate against source knowledge
			quality := pair.Quality
			if sp.ValidatePair != nil {
				quality = sp.ValidatePair(pair, chunk.Content)
			}

			sp.mu.Lock()
			sp.TotalGenerated++
			sp.mu.Unlock()

			if quality >= sp.config.MinQuality {
				pair.Quality = quality
				sp.StorePair(pair)
				accepted++

				sp.mu.Lock()
				sp.TotalAccepted++
				sp.mu.Unlock()

				slog.Debug("selfplay: accepted pair",
					"q", truncate(pair.Question, 50),
					"quality", fmt.Sprintf("%.2f", quality))
			} else {
				sp.mu.Lock()
				sp.TotalRejected++
				sp.mu.Unlock()
			}
		}
	}

	slog.Info("selfplay: session complete",
		"accepted", accepted,
		"total_generated", sp.TotalGenerated,
		"total_accepted", sp.TotalAccepted)

	return accepted
}

// Stats returns self-play statistics.
func (sp *SelfPlay) Stats() (generated, accepted, rejected int) {
	sp.mu.Lock()
	defer sp.mu.Unlock()
	return sp.TotalGenerated, sp.TotalAccepted, sp.TotalRejected
}

func truncate(s string, n int) string {
	s = strings.TrimSpace(s)
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
